"""add jobs table

Revision ID: 3efe89b3aef3
Revises: 
Create Date: 2026-05-19 09:34:39.611481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efe89b3aef3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ticket_status_enum', create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('download_url', sa.String(length=1000), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
    op.execute('DROP TYPE ticket_status_enum;')